version: "3.8"

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    environment:
      - ENV=dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
  elasticsearch:
    image: elasticsearch:8.13.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  logstash:
    image: logstash:8.13.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/var/log
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.13.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
