name: "Create Infrastructure Branch Based Deployment"

on:
  workflow_dispatch:
    inputs:
      environment_name:
        type: choice
        description: "Select the environment name"
        options:
          - prod
      resource:
        type: choice
        description: "Select the resources name"
        options:
          - ec2-instance
          - s3
      tf_function:
        type: choice
        description: "infrastructure planning / deployment"
        options:
          - plan
          - apply

env:
  TERRAFORM_VERSION: 1.8.5
  TERRAGRUNT_VERSION: v0.59.4
jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: ap-south-1

      - name: Set tg path and install checkov
        id: set-folder
        run: |
          echo "tg_dir=terragrunt/${{ env.resource_env }}/${{ inputs.environment_name }}/${{ inputs.resource }}" >> $GITHUB_ENV

      - name: Terraform Validate
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ env.tg_dir }}
          tg_command: 'validate '

      - name: Terraform Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ env.tg_dir }}
          tg_command: 'plan '
        id: terraform-plan

      - name: Deploy
        if: inputs.tf_function == 'apply'
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ env.tg_dir }} 
          tg_command: 'apply'
